-- Usuários
insert into workshop (id, name, description) 
values ('recodiesel_id', 'RECODIESEL', 'Descricao da oficina');

insert into users (id, name, login, password, role, workshop_id) 
values ('f8d1e2e0-739a-4af8-b72a-79044ccc03f0', 
	    'Admin', 
	    'admin@railcontrol.com', 
	    '$2a$10$xDhFXJM95Ok4W2b9aLpoz.j5MZkml8IRPyshmR9zI9qdpYxV/mifu', 
	    'ADMIN',
	    'recodiesel_id'
);

insert into users (id, name, login, password, role, workshop_id) 
values ('2933d5c4-3b47-4355-acf9-b24e358740d1', 
	    'Operador', 
	    'oper@railcontrol.com', 
	    '$2a$10$JFwfkqn3CH3zvuUC4M9VzuVBCpqrnCPE5Hi6JUz1LVeCrBvKlYZNa', 
	    'OPERATOR',
	    'recodiesel_id'
);

 -- Veiculos
insert into vehicle (id, plate, model, year_model, owner, workshop_id) values ('VCL1111', 'ABC1111', 'FORD 01', '2017/2018', 'Fulano de Tal', 'recodiesel_id');
insert into vehicle (id, plate, model, year_model, owner, workshop_id) values ('VCL2222', 'ABC2222', 'FORD 02', '2020/2020', 'Sicrano Silva', 'recodiesel_id');
insert into vehicle (id, plate, model, year_model, owner, workshop_id) values ('VCL3333', 'ABC3333', 'FORD 03', '2021/2022', 'Beltrano Costa', 'recodiesel_id');
insert into vehicle (id, plate, model, year_model, owner, workshop_id) values ('VCL4444', 'ABC4444', 'FORD 04', '2023/2023', 'Fulano Pereira', 'recodiesel_id');

-- Injetores
insert into injector (id, model, plan_id, description, workshop_id) values ('INJ1111', '0445110231', 'PLN000001', 'Modelo de injetor para teste', 'recodiesel_id');	
insert into injector (id, model, plan_id, description, workshop_id) values ('INJ2222', '0445110190', 'PLN000002', 'Modelo de injetor para teste', 'recodiesel_id');	
insert into injector (id, model, plan_id, description, workshop_id) values ('INJ3333', '0445110520', 'PLN000003', 'Modelo de injetor para teste', 'recodiesel_id');	
insert into injector (id, model, plan_id, description, workshop_id) values ('INJ4444', '0445110374', 'PLN000004', 'Modelo de injetor para teste', 'recodiesel_id');							 

-- Planos
insert into plan (
	id,
	code,
	type,
	description,
	max_resistance,
	min_resistance,
	max_reactance,
	min_reactance,
	max_isolation,
	min_isolation,
	max_half_load,
	min_half_load,
	half_load_pressure,
	max_full_load,
	min_full_load,
	full_load_pressure,
	max_idling,
	min_idling,
	idling_pressure,
	max_pre_injection,
	min_pre_injection,
	pre_injection_pressure,
	max_half_load_return,
	min_half_load_return,
	max_full_load_return,
	min_full_load_return,
	max_idling_return,
	min_idling_return,
	max_pre_injection_return,
	min_pre_injection_return, 
	half_load_bench_rpm,
	half_load_pulse_time,
	half_load_frequency,
	full_load_bench_rpm,
	full_load_pulse_time,
	full_load_frequency,
	idling_bench_rpm,
	idling_pulse_time,
	idling_frequency,
	pre_injection_bench_rpm,
	pre_injection_pulse_time,
	pre_injection_frequency,
	workshop_id
) values (
	'PLN000001',
	'PLANO_01',
	'INDUTIVO',
	'Teste plano 01',
	700,
	300,
	380,
	195,
	null,
	270,
	28,
	22,
	800,
	55,
	45,
	1400,
	7,
	5,
	300,
	4,
	2,
	700,
	15,
	0,
	25,
	0,
	12, 
	0,
	5,
	0,
	1300,
	1,
	1000,
	1300,
	1,
	1500,
	450,
	1,
	400,
	400,
	2,
	150,	
	'recodiesel_id'
);

insert into plan (
	id,
	code,
	type,
	description,
	max_resistance,
	min_resistance,
	max_reactance,
	min_reactance,
	max_isolation,
	min_isolation,
	max_half_load,
	min_half_load,
	half_load_pressure,
	max_full_load,
	min_full_load,
	full_load_pressure,
	max_idling,
	min_idling,
	idling_pressure,
	max_pre_injection,
	min_pre_injection,
	pre_injection_pressure,
	max_half_load_return,
	min_half_load_return,
	max_full_load_return,
	min_full_load_return,
	max_idling_return,
	min_idling_return,
	max_pre_injection_return,
	min_pre_injection_return,
	half_load_bench_rpm,
	half_load_pulse_time,
	half_load_frequency,
	full_load_bench_rpm,
	full_load_pulse_time,
	full_load_frequency,
	idling_bench_rpm,
	idling_pulse_time,
	idling_frequency,
	pre_injection_bench_rpm,
	pre_injection_pulse_time,
	pre_injection_frequency,
	workshop_id
) values (
	'PLN000002',
	'PLANO_02',
	'INDUTIVO',
	'Teste plano 02',
	560,
	275,
	420,
	130,
	null,
	270,
	28,
	22,
	800,
	55,
	45,
	1400,
	7,
	5,
	300,
	4,
	2,
	700,
	15,
	0,
	25,
	0,
	12, 
	0,
	5,
	0,
	1300,
	1,
	1000,
	1300,
	1,
	1500,
	450,
	1,
	400,
	400,
	2,
	150,	
	'recodiesel_id'
);

insert into plan (
	id,
	code,
	type,
	description,
	max_resistance,
	min_resistance,
	max_reactance,
	min_reactance,
	max_isolation,
	min_isolation,
	max_half_load,
	min_half_load,
	half_load_pressure,
	max_full_load,
	min_full_load,
	full_load_pressure,
	max_idling,
	min_idling,
	idling_pressure,
	max_pre_injection,
	min_pre_injection,
	pre_injection_pressure,
	max_half_load_return,
	min_half_load_return,
	max_full_load_return,
	min_full_load_return,
	max_idling_return,
	min_idling_return,
	max_pre_injection_return,
	min_pre_injection_return,
	half_load_bench_rpm,
	half_load_pulse_time,
	half_load_frequency,
	full_load_bench_rpm,
	full_load_pulse_time,
	full_load_frequency,
	idling_bench_rpm,
	idling_pulse_time,
	idling_frequency,
	pre_injection_bench_rpm,
	pre_injection_pulse_time,
	pre_injection_frequency,
	workshop_id
) values (
	'PLN000003',
	'HILUX 2.5',
	'INDUTIVO',
	'Plano de Teste 2005 a 2010',
	120,
	80,
	78,
	34,
	null,
	270,
	28,
	22,
	800,
	55,
	45,
	1400,
	7,
	5,
	300,
	4,
	2,
	700,
	15,
	0,
	25,
	0,
	12, 
	0,
	5,
	0,
	1300,
	1,
	1000,
	1300,
	1,
	1500,
	450,
	1,
	400,
	400,
	2,
	150,	
	'recodiesel_id'
);

insert into plan (
	id,
	code,
	type,
	description,
	max_resistance,
	min_resistance,
	max_reactance,
	min_reactance,
	max_isolation,
	min_isolation,
	max_half_load,
	min_half_load,
	half_load_pressure,
	max_full_load,
	min_full_load,
	full_load_pressure,
	max_idling,
	min_idling,
	idling_pressure,
	max_pre_injection,
	min_pre_injection,
	pre_injection_pressure,
	max_half_load_return,
	min_half_load_return,
	max_full_load_return,
	min_full_load_return,
	max_idling_return,
	min_idling_return,
	max_pre_injection_return,
	min_pre_injection_return,
	half_load_bench_rpm,
	half_load_pulse_time,
	half_load_frequency,
	full_load_bench_rpm,
	full_load_pulse_time,
	full_load_frequency,
	idling_bench_rpm,
	idling_pulse_time,
	idling_frequency,
	pre_injection_bench_rpm,
	pre_injection_pulse_time,
	pre_injection_frequency,
	workshop_id
) values (
	'PLN000004',
	'PLANO_04',
	'PIEZO_ELETRICO',
	'Teste plano 04',
	340,
	130,
	450,
	230,
	null,
	270,
	28,
	22,
	800,
	55,
	45,
	1400,
	7,
	5,
	300,
	4,
	2,
	700,
	15,
	0,
	25,
	0,
	12, 
	0,
	5,
	0,
	1300,
	1,
	1000,
	1300,
	1,
	1500,
	450,
	1,
	400,
	400,
	2,
	150,
	'recodiesel_id'
);
